# Generated by Django 4.2.6 on 2023-10-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microservice_chat", "0003_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_origin",
            field=models.IntegerField(max_length=100, null=True, unique=True),
        ),
    ]
