# Generated by Django 3.2.19 on 2023-12-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservice_chat', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
