# Generated by Django 4.2.6 on 2023-10-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "microservice_chat",
            "0006_alter_user_options_user_date_joined_user_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_origin",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
