# Generated by Django 3.2.19 on 2023-12-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice_chat', '0006_chatmessage_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='foto',
        ),
    ]
