# Generated by Django 4.2.6 on 2023-10-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microservice_chat", "0007_alter_user_id_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=30),
        ),
    ]
